### PR TITLE
Data Wrangling and Data Visualization Tutorials

### PR DESCRIPTION
**Pull request by storopoli**
This PR addes the Data Wrangling and Plotting Tutorials to the list at tutorials.pumas.ai.

The only thing that I found that is supposed to be the recipient of this content are the `README.md` and the `docs/index.html`. If the `index.html` is machine- or script-generated please advise me what file I need to alter.

Below you can find a screenshot of the proposed changes rendered in a browser.

image

### CODE REVIEW

**Review by vjd — APPROVED** [review]
For now let's just give these links instead of placing the htmls in the docs folder. We can always change it later.

**Comment by storopoli** [comment]
Does it auto build? What do we need to now to have this updated at tutorials.pumas.ai?

**Comment by storopoli** [comment]
@MichaelHatherly do you how do we update tutorials.pumas.ai?

**Comment by vjd** [comment]
you have to create a new tag

**Comment by storopoli** [comment]
Ok, I've created and also made a new release. 
https://github.com/PumasAI/PumasTutorials.jl/releases/tag/v2.0.3

**Comment by vjd** [comment]
hmm.. but you tag and releae DataWrangling and PlotttinginJulia? That is where the tags need to come

**Comment by vjd** [comment]
my bad - should have been more explicit

**Comment by storopoli** [comment]
I am waiting for the logo PRs to tag a new release

https://github.com/PumasAI/DataWranglingInJulia/pull/69
https://github.com/PumasAI/PlottingInJulia/pull/40

**Comment by storopoli** [comment]
done the tags and releases in both `DataWrangling` and `PlottingInJulia`.

**Pull request merged**
