### PR TITLE
Update manifest and project files to match PumasSystemImages

### PR DESCRIPTION
**Pull request by andreasnoack**
This should be sufficient for part II of the intro tutorial.

### CODE REVIEW

**Comment by vjd** [comment]
Thank you!

**Comment by vjd** [comment]
Can I merge this and rebase my branch? It looks like some other packages got an update in the system image?

**Comment by andreasnoack** [comment]
Yes. I'll have to update this PR. I'll do it as soon as the system image tests go through. ~20 minutes.

**Comment by vjd** [comment]
The master has the newer images and this PR can be closed

**Pull request closed without merging**
