### PR TITLE
Update GSA tutorials

### PR DESCRIPTION
**Pull request by Vaibhavdixit02**
I am guessing we don't have capability to run stuff here in CI right? 
Will build the voriconazole tutorial on a server and push that as well, currently only updated `.jmd` for it

### CODE REVIEW

**Comment by Vaibhavdixit02** [comment]
I am going to merge this now, with https://github.com/PumasAI/PumasTutorials.jl/pull/103/commits/834a75baa94aa83a1b535b8b5ceaf32e68f52847 I think it should render on the website?

**Comment by andreasnoack** [comment]
@vjd Are we sure that we'd like the updated tutorials to go live before the release?

**Comment by andreasnoack** [comment]
Just checked and we are using GitLab pages for the deployment which means that the website is only updated when the deploy step of the CI succeeds. I'd have to update the token before that happens so right now you won't see the tutorials show up on the website. You can see in https://github.com/PumasAI/PumasTutorials.jl/blob/b878fb5a3fe0e8aba45f37360a938b4913d0cfb0/.gitlab-ci.yml#L38-L41

that everything from the html folder is copied to the website folder but if we add new tutorials then index.html would have to be updated. (It could also use some layout work. It's not that pretty).

**Comment by Vaibhavdixit02** [comment]
> we add new tutorials then index.html would have to be updated.

Yeah done that in https://github.com/PumasAI/PumasTutorials.jl/commit/834a75baa94aa83a1b535b8b5ceaf32e68f52847

>I'd have to update the token before that happens so right now you won't see the tutorials show up on the website.

Would you be able to do that now?

**Comment by Vaibhavdixit02** [comment]
Oh crap, I pushed `.toml`s from the arctic run that's what is breaking the CI. Opening PR with updated ones right away

**Comment by andreasnoack** [comment]
How do you see that. I think CI is failing because it cannot access the Pumas package server

**Comment by Vaibhavdixit02** [comment]
https://gitlab.com/PumasAI/PumasTutorials-jl/-/jobs/1212117559#L131

It's failing because it's trying to clone private repositories https://gitlab.com/PumasAI/PumasTutorials-jl/-/jobs/1212117559#L132 I think

**Comment by vjd** [comment]
In this branch, I just updated the project and manifest files to 2.0. Maybe we need coordination here :)

**Comment by Vaibhavdixit02** [comment]
>In this branch, I just updated the project and manifest files to 2.0. Maybe we need coordination here :)

Which branch? 

Yeah I am rushing here to be able to record the video and submit before tonight haha, need a link available for that

**Comment by vjd** [comment]
https://github.com/PumasAI/PumasTutorials.jl/tree/vjd/introtopumas1update

**Comment by andreasnoack** [comment]
I think we might need to use a manifest for each tutorial or maybe for each group of tutorials. Otherwise, it would be quite heavy to update the manifest since it would require us to rerun all tutorials, some of which are quite heavy.

**Pull request merged**
