### PR TITLE
Syntax Updates

### PR DESCRIPTION
**Pull request by chriselrod**
Trivial changes so far.

I got a segfault on Julia 1.5 from `read_nca`; I'll start looking into it shortly:
```julia
julia> pop = read_nca(data, llq=0concu, timeu=timeu, concu=concu, amtu=amtu)

signal (11): Segmentation fault
in expression starting at REPL[128]:1
isVectorTy at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/include/llvm/IR/Type.h:229 [inlined]
isExtendedVector at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/lib/CodeGen/ValueTypes.cpp:59
isVector at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/include/llvm/CodeGen/ValueTypes.h:151 [inlined]
getScalarType at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/include/llvm/CodeGen/ValueTypes.h:260
getScalarSizeInBits at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/include/llvm/CodeGen/ValueTypes.h:298 [inlined]
SimplifyDemandedBits at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/lib/CodeGen/SelectionDAG/TargetLowering.cpp:1569
SimplifyDemandedBits at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/lib/CodeGen/SelectionDAG/TargetLowering.cpp:863
SimplifyDemandedBits at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:1225 [inlined]
SimplifyDemandedBits at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:300 [inlined]
SimplifyDemandedBits at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:293
visitOR at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:5891
combine at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:1801
Run at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:1625 [inlined]
Combine at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/lib/CodeGen/SelectionDAG/DAGCombiner.cpp:20876
CodeGenAndEmitDAG at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:817
SelectAllBasicBlocks at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:1588
runOnMachineFunction at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp:500
runOnMachineFunction at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/lib/Target/X86/X86ISelDAGToDAG.cpp:194
runOnFunction at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/lib/CodeGen/MachineFunctionPass.cpp:73 [inlined]
runOnFunction at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/lib/CodeGen/MachineFunctionPass.cpp:38
runOnFunction at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/lib/IR/LegacyPassManager.cpp:1648
runOnModule at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/lib/IR/LegacyPassManager.cpp:1685
runOnModule at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/lib/IR/LegacyPassManager.cpp:1750 [inlined]
run at /home/chriselrod/Documents/languages/juliarelease/deps/srccache/llvm-9.0.1/lib/IR/LegacyPassManager.cpp:1863
operator() at /home/chriselrod/Documents/languages/juliarelease/src/jitlayers.cpp:522
addModule at /home/chriselrod/Documents/languages/juliarelease/usr/include/llvm/ExecutionEngine/Orc/IRCompileLayer.h:93 [inlined]
addModule at /home/chriselrod/Documents/languages/juliarelease/src/jitlayers.cpp:648
jl_add_to_ee at /home/chriselrod/Documents/languages/juliarelease/src/jitlayers.cpp:893 [inlined]
jl_add_to_ee at /home/chriselrod/Documents/languages/juliarelease/src/jitlayers.cpp:955
jl_add_to_ee at /home/chriselrod/Documents/languages/juliarelease/src/jitlayers.cpp:977 [inlined]
_jl_compile_codeinst at /home/chriselrod/Documents/languages/juliarelease/src/jitlayers.cpp:126
jl_generate_fptr at /home/chriselrod/Documents/languages/juliarelease/src/jitlayers.cpp:302
jl_compile_method_internal at /home/chriselrod/Documents/languages/juliarelease/src/gf.c:1964
jl_compile_method_internal at /home/chriselrod/Documents/languages/juliarelease/src/gf.c:1931 [inlined]
_jl_invoke at /home/chriselrod/Documents/languages/juliarelease/src/gf.c:2224 [inlined]
jl_apply_generic at /home/chriselrod/Documents/languages/juliarelease/src/gf.c:2398
#NCASubject#1 at /home/chriselrod/.julia/dev/Pumas.jl/src/nca/type.jl:201
Type##kw at /home/chriselrod/.julia/dev/Pumas.jl/src/nca/type.jl:116
unknown function (ip: 0x7fe1ea0568c1)
#___read_nca#177 at /home/chriselrod/.julia/dev/Pumas.jl/src/nca/data_parsing.jl:182
___read_nca##kw at /home/chriselrod/.julia/dev/Pumas.jl/src/nca/data_parsing.jl:51 [inlined]
#read_nca#172 at /home/chriselrod/.julia/dev/Pumas.jl/src/nca/data_parsing.jl:22
read_nca##kw at /home/chriselrod/.julia/dev/Pumas.jl/src/nca/data_parsing.jl:21
unknown function (ip: 0x7fe1ea04fdcc)
jl_apply at /home/chriselrod/Documents/languages/juliarelease/src/julia.h:1690 [inlined]
do_call at /home/chriselrod/Documents/languages/juliarelease/src/interpreter.c:117
eval_value at /home/chriselrod/Documents/languages/juliarelease/src/interpreter.c:206
eval_stmt_value at /home/chriselrod/Documents/languages/juliarelease/src/interpreter.c:157 [inlined]
eval_body at /home/chriselrod/Documents/languages/juliarelease/src/interpreter.c:552
jl_interpret_toplevel_thunk at /home/chriselrod/Documents/languages/juliarelease/src/interpreter.c:660
jl_toplevel_eval_flex at /home/chriselrod/Documents/languages/juliarelease/src/toplevel.c:840
jl_toplevel_eval_flex at /home/chriselrod/Documents/languages/juliarelease/src/toplevel.c:790
jl_toplevel_eval_flex at /home/chriselrod/Documents/languages/juliarelease/src/toplevel.c:790
jl_toplevel_eval at /home/chriselrod/Documents/languages/juliarelease/src/toplevel.c:849 [inlined]
jl_toplevel_eval_in at /home/chriselrod/Documents/languages/juliarelease/src/toplevel.c:883
eval at ./boot.jl:331
eval_user_input at /home/chriselrod/Documents/languages/juliarelease/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:134
repl_backend_loop at /home/chriselrod/Documents/languages/juliarelease/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:195
start_repl_backend at /home/chriselrod/Documents/languages/juliarelease/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:180
#run_repl#37 at /home/chriselrod/Documents/languages/juliarelease/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:292
run_repl at /home/chriselrod/Documents/languages/juliarelease/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:288
#806 at ./client.jl:399
jfptr_YY.806_41524 at /home/chriselrod/Documents/languages/juliarelease/usr/lib/julia/sys.so (unknown line)
jl_apply at /home/chriselrod/Documents/languages/juliarelease/src/julia.h:1690 [inlined]
do_apply at /home/chriselrod/Documents/languages/juliarelease/src/builtins.c:655
jl_f__apply at /home/chriselrod/Documents/languages/juliarelease/src/builtins.c:669 [inlined]
jl_f__apply_latest at /home/chriselrod/Documents/languages/juliarelease/src/builtins.c:705
#invokelatest#1 at ./essentials.jl:710 [inlined]
invokelatest at ./essentials.jl:709 [inlined]
run_main_repl at ./client.jl:383
exec_options at ./client.jl:313
_start at ./client.jl:506
jfptr__start_57504 at /home/chriselrod/Documents/languages/juliarelease/usr/lib/julia/sys.so (unknown line)
jl_apply at /home/chriselrod/Documents/languages/juliarelease/ui/../src/julia.h:1690 [inlined]
true_main at /home/chriselrod/Documents/languages/juliarelease/ui/repl.c:106
main at /home/chriselrod/Documents/languages/juliarelease/ui/repl.c:227
__libc_start_main at /usr/lib64/haswell/libc.so.6 (unknown line)
_start at /home/chriselrod/Documents/languages/juliarelease/usr/bin/julia (unknown line)
Allocations: 465666178 (Pool: 465543347; Big: 122831); GC: 192
fish: “~/Documents/languages/juliarele…” terminated by signal SIGSEGV (Address boundary error)
```

### CODE REVIEW

**Comment by andreasnoack** [comment]
Did you use the official open source Julia 1.5 from julialang.org?

Which CPU were you using? Could you try switching to older instruction sets and see if it affects the segfault?

**Comment by chriselrod** [comment]
I tried it on:
* Official binary of 1.4.1: works
* Official binary of 1.5.0: segfault
* Compiled-from-source 1.5.1-pre: segfault (this was where the above came from)

```julia
julia> versioninfo()
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i9-10980XE CPU @ 3.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
```

**Comment by chriselrod** [comment]
In case rr helps, you should be able to replay the bug with:
```julia
julia> using BugReporting

julia> replay("https://s3.amazonaws.com/julialang-dumps/reports/2020-08-06T19-53-54-chriselrod.tar.zst")
```

**Comment by andreasnoack** [comment]
> I do not get a segfault when starting with -Chaswell. So the instruction set is in fact relevant here.

Great. It probably narrows down the possible places where things can go wrong.

> How did you predict it'd be involved?

It was mostly a guess but

1. I'm pretty sure that the code path is exercised by our tests and we switched to testing on 1.5 about a week ago and it didn't hit the issue. CI is typically not running on the most recent architectures. 
2. It looks like the problem is in codegen.
3. I've seen LLVM/codegen issues with new architectures a couple of times before

> Skimming through NCASubject or cleanblq, I don't see anything that looks particularly low-level / likely to cause such problems.

I agree that there is nothing there that should cause a segfault but `cleanblq` does seem like a pretty big function to inline.

**Comment by chriselrod** [comment]
> I'm pretty sure that the code path is exercised by our tests and we switched to testing on 1.5 about a week ago and it didn't hit the issue. CI is typically not running on the most recent architectures.

Tests did pass locally, and Linux Travis CI has AVX512.

> I agree that there is nothing there that should cause a segfault but cleanblq does seem like a pretty big function to inline.

Inlining does happen at the Julia level, but LLVM doesn't like gigantic functions, so that could still cause problems.

FWIW, I get the crash if I comment out [lines 203 through 219](https://github.com/PumasAI/Pumas.jl/blob/bbd8ba0fd6b4689ef546474f8d2489cc12e08234/src/nca/utils.jl#L203-L219), but not if I comment out the entire loop.
So I suspect, as implied by the llvm IR Keno posted which showed a problem with a bit-mask, that the problem comes from one of the `mask` definitions for some combination of `conc` and `time` types.

**Comment by andreasnoack** [comment]
Superseded by #64

**Pull request closed without merging**
